flask_qa/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

from flask_qa.extensions import db
from flask_qa.models import Restaurant, User,\
    Rating, Salary, Warnings, Question, \
    Ingredient, Supplier, Ingredientsupplier, \
    Supplyorder, Ingredientorder, Food, Recipe, \
    Menu, Dish, Order, Orderfood

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        unhashed_password = request.form['password']
        creditCardNumber = request.form['creditCardNumber']
        latitude = request.form['latitude']
        longitude = request.form['longitude']
        requestedRole = request.form['role']
        restaurant_id = request.form['restaurant_id']
        role = 'visitor'

        user = User(
            name=name, 
            unhashed_password=unhashed_password,
            creditCardNumber=creditCardNumber,
            latitude=latitude,
            longitude=longitude,
            role=role,
            requestedRole=requestedRole,
            restaurant_id=restaurant_id
        )

        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for('auth.login'))
    restaurants = db.session.query(Restaurant).all()
    context = {
        'restaurants' : restaurants
    }
    return render_template('register.html', **context)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']

        user = User.query.filter_by(name=name).first()

        error_message = ''

        if not user or not check_password_hash(user.password, password):
            error_message = 'Could not login. Please check and try again.'

        if not error_message:
            login_user(user)
            return redirect(url_for('main.index'))

    return render_template('login.html')

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

flask_qa/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy.sql import func

from flask_qa.extensions import db

from flask_qa.models import Restaurant, User,\
    Rating, Salary, Warnings, Question, \
    Ingredient, Supplier, Ingredientsupplier, \
    Supplyorder, Ingredientorder, Food, Recipe, Dishrating, \
    Menu, Dish, Order, Orderfood
import logging
main = Blueprint('main', __name__)

@main.route('/')
def index():
    questions = Question.query.filter(Question.answer != None).all()

    context = {
        'questions' : questions
    }

    return render_template('home.html', **context)

@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    if request.method == 'POST':
        question = request.form['question']
        expert = request.form['expert']

        question = Question(
            question=question, 
            expert_id=expert, 
            asked_by_id=current_user.id
        )

        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main.index'))

    experts = User.query.filter(User.role != 'visitor').all()

    context = {
        'experts' : experts
    }

    return render_template('ask.html', **context)

@main.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    if (current_user.role == 'Visitor'):
        return redirect(url_for('main.index'))

    question = Question.query.get_or_404(question_id)

    if request.method == 'POST':
        question.answer = request.form['answer']
        db.session.commit()

        return redirect(url_for('main.unanswered'))

    context = {
        'question' : question
    }

    return render_template('answer.html', **context)

@main.route('/question/<int:question_id>')
def question(question_id):
    question = Question.query.get_or_404(question_id)

    context = {
        'question' : question
    }

    return render_template('question.html', **context)

@main.route('/unanswered')
@login_required
def unanswered():
    if (current_user.role == 'Visitor'):
        return redirect(url_for('main.index'))

    unanswered_questions = Question.query\
        .filter_by(expert_id=current_user.id)\
        .filter(Question.answer == None)\
        .all()

    context = {
        'unanswered_questions' : unanswered_questions
    }

    return render_template('unanswered.html', **context)
    
@main.route('/salary/<int:salary_id>', methods=['GET', 'POST'])
@login_required
def salary(salary_id):
    if (current_user.role == 'Registered' or current_user.role == 'Visitor'):
        return redirect(url_for('main.index'))

    salary = Salary.query.get(int(salary_id))
    
    salary.salary_value = int(request.form['amount'])
    db.session.commit()

    return redirect(url_for('main.employee'))

@main.route('/employee')
@login_required
def employee():
    if not (current_user.role == 'Manager'):
        return redirect(url_for('main.index'))

    employees = db.session.query(User, Salary)\
        .filter(User.id == Salary.user_id)\
        .filter_by(restaurant_id = current_user.restaurant_id)\
        .filter(User.role != 'Registered')\
        .filter(User.role != 'Visitor')\
        .all()

    context = {
        'employees' : employees
    }

    return render_template('employee.html', **context)

@main.route('/salesorder')
@login_required
def salesorder():
    if not (current_user.role == 'Manager'):
        return redirect(url_for('main.index'))

    salesorder = db.session.query(Supplyorder)\
        .filter_by(restaurant_id = current_user.restaurant_id)\
        .all()

    context = {
        'salesorder' : salesorder
    }

    return render_template('salesorder.html', **context)

@main.route('/createsalesorder', methods=['GET', 'POST'])
@login_required
def createsalesorder():
    if (current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    order_description = request.form['salesordertext']
    salesorder = Supplyorder(
        supply_order_name = order_description,
        approval = False,
        restaurant_id = current_user.restaurant_id
    )
    db.session.add(salesorder)
    db.session.commit()

    return redirect(url_for('main.salesorder'))

@main.route('/accept/<int:supply_order_id>')
@login_required
def acceptorder(supply_order_id):
    if (current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    supplyorder = Supplyorder.query.get_or_404(supply_order_id)

    supplyorder.approval = True
    db.session.commit()

    return redirect(url_for('main.salesorder'))

@main.route('/addsalesingredient', methods=['GET', 'POST'])
@login_required
def addsalesingredient():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    ingredientorder = Ingredientorder(
        supply_order_id = request.form['supply_order_id'],
        ingredient_supplier_id = request.form['ingredient_supplier_id'],
        amount = request.form['amount']
    )
    db.session.add(ingredientorder)
    db.session.commit()

    return redirect(url_for('main.managesalesorder'))

@main.route('/managesalesorder')
@login_required
def managesalesorder():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    salesorderlist = db.session.query(Supplyorder,\
         Ingredientorder,Ingredientsupplier, Supplier, Ingredient)\
        .filter(Supplyorder.approval == False)\
        .filter(Supplyorder.supply_order_id == Ingredientorder.supply_order_id)\
        .filter(Supplyorder.restaurant_id == current_user.restaurant_id)\
        .filter(Ingredientorder.ingredient_supplier_id == Ingredientsupplier.ingredient_supplier_id)\
        .filter(Ingredientsupplier.ingredient_id == Ingredient.ingredient_id)\
        .filter(Ingredientsupplier.supplier_id == Supplier.supplier_id)\
        .order_by(Supplyorder.supply_order_id)\
        .all()
    ingredientsupplierlist = db.session.query(Ingredientsupplier, Supplier, Ingredient)\
        .filter(Ingredientsupplier.ingredient_id == Ingredient.ingredient_id)\
        .filter(Ingredientsupplier.supplier_id == Supplier.supplier_id)\
        .all()
    context = {
        'incompletesalesorder' : salesorderlist,
        'ingredientsupply' : ingredientsupplierlist
    }

    return render_template('managesalesorder.html', **context)

@main.route('/users')
@login_required
def users():
    if (current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    users = User.query.filter_by(restaurant_id = current_user.restaurant_id).all()

    context = {
        'users' : users
    }

    return render_template('users.html', **context)

@main.route('/promote/<int:user_id>')
@login_required
def promote(user_id):
    if (current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    user = User.query.get_or_404(user_id)

    user.role = user.requestedRole
    salary = Salary(
        user_id = user_id,
        salary_value = 0
    )
    db.session.add(salary)
    db.session.commit()

    return redirect(url_for('main.users'))

@main.route('/addingredient', methods=['GET', 'POST'])
@login_required
def addingredient():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    ingredient = Ingredient(
        ingredient_name = request.form['ingredient_name']
    )
    db.session.add(ingredient)
    db.session.commit()

    return redirect(url_for('main.manageingredients'))

@main.route('/addsupplier', methods=['GET', 'POST'])
@login_required
def addsupplier():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    supplier = Supplier(
        supplier_name = request.form['supplier_name']
    )
    db.session.add(supplier)
    db.session.commit()

    return redirect(url_for('main.manageingredients'))

@main.route('/addingredientsupplier', methods=['GET', 'POST'])
@login_required
def addingredientsupplier():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    ingredientsupplier = Ingredientsupplier(
        price = request.form['price'],
        ingredient_id = request.form['ingredient_id'],
        supplier_id = request.form['supplier_id']
    )
    db.session.add(ingredientsupplier)
    db.session.commit()

    return redirect(url_for('main.manageingredients'))

@main.route('/manageingredients')
@login_required
def manageingredients():
    if (current_user.role != 'Salesmanager' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    suppliers = db.session.query(Supplier).all()
    ingredients = db.session.query(Ingredient).all()
    ingredientsuppliers = db.session.query(Ingredientsupplier, Supplier, Ingredient)\
        .filter(Ingredientsupplier.ingredient_id == Ingredient.ingredient_id)\
        .filter(Ingredientsupplier.supplier_id == Supplier.supplier_id)\
        .all()
    
    context = {
        'suppliers' : suppliers,
        'ingredients' : ingredients,
        'ingredientsuppliers' : ingredientsuppliers
    }

    return render_template('manageingredients.html', **context)

@main.route('/addmenu', methods=['GET', 'POST'])
@login_required
def addmenu():
    if (current_user.role != 'Chef' and current_user.role != 'Manager'):
        return redirect(url_for('main.index'))

    menu = Menu(
        menu_name = request.form['menu_name'],
        restaurant_id = current_user.restaurant_id
    )
    db.session.add(menu)
    db.session.commit()

    return redirect(url_for('main.managemenu'))

@main.route('/addfood', methods=['GET', 'POST'])
@login_required
def addfood():
    if (current_user.role != 'Chef' and current_user.role != 'Manager'):

flask_qa/templates/answer.html
{% extends 'base.html' %}
{% block title %}Answer Question{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>{{ question.question }}</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.answer', question_id=question.id) }}">
                <fieldset>
                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">Answer</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" name="answer" rows="3" id="textArea"></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
    
    <link href="{{ url_for('static', filename='theme.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='rate.css') }}" rel="stylesheet">
    <title>Map</title>
    <style>
    #myMap {
      height: 350px;
      width: 680px;
    }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgtkU7xkzIcbFq8A3Hhn627ddv6hmzgDw&sensor=false">
    </script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
    </script>
    <script type="text/javascript"> 
    var map;
    var marker;
    var myLatlng = new google.maps.LatLng(40.80789944202298,-73.9632397653138);
    var geocoder = new google.maps.Geocoder();
    var infowindow = new google.maps.InfoWindow();
      function initialize(){
      var mapOptions = {
      zoom: 18,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    
    map = new google.maps.Map(document.getElementById("myMap"), mapOptions);
    
    marker = new google.maps.Marker({
      map: map,
      position: myLatlng,
      draggable: true 
    }); 
    geocoder.geocode({'latLng': myLatlng }, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        if (results[0]) {
          $('#latitude,#longitude').show();
          $('#address').val(results[0].formatted_address);
          $('#latitude').val(marker.getPosition().lat());
          $('#longitude').val(marker.getPosition().lng());
          infowindow.setContent(results[0].formatted_address);
          infowindow.open(map, marker);
        }
      }
      
    });
    
    google.maps.event.addListener(marker, 'dragend', function() {
    
    geocoder.geocode({'latLng': marker.getPosition()}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        if (results[0]) {
          $('#address').val(results[0].formatted_address);
          $('#latitude').val(marker.getPosition().lat());
          $('#longitude').val(marker.getPosition().lng());
          infowindow.setContent(results[0].formatted_address);
          infowindow.open(map, marker);
        }
      }
    });
  });
    
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Sushi Restaurant Online System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.ask') }}">Ask Question</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Manager') %}
            <li><a href="{{ url_for('main.unanswered') }}">Unanswered Questions</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Manager') %}
            <li><a href="{{ url_for('main.users') }}">User Setup</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Manager') %}
            <li><a href="{{ url_for('main.employee') }}">Employees</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Manager') %}
            <li><a href="{{ url_for('main.salesorder') }}">Accept Sales order</a></li>
            {% endif %}
            {% if current_user.is_authenticated and ((current_user.role == 'Salesmanager') or (current_user.role == 'Manager')) %}
            <li><a href="{{ url_for('main.managesalesorder') }}">Add to sales order</a></li>
            {% endif %}
            {% if current_user.is_authenticated and ((current_user.role == 'Salesmanager') or (current_user.role == 'Manager')) %}
            <li><a href="{{ url_for('main.manageingredients') }}">Manage ingredients and suppliers</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Chef' or (current_user.role == 'Manager')) %}
            <li><a href="{{ url_for('main.managemenu') }}">Manage Menu</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role == 'Chef' or (current_user.role == 'Manager') or (current_user.role == 'salesManager')) %}
            <li><a href="{{ url_for('main.managefoodingredients') }}">Manage food ingredients</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role != 'Visitor' and current_user.role != 'Blacklisted') %}
            <li><a href="{{ url_for('main.rating') }}">Rate</a></li>
            {% endif %}
            {% if current_user.is_authenticated and (current_user.role != 'Blacklisted') %}
            <li><a href="{{ url_for('main.customermenu') }}">customermenu</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
      {{ current_user.role }}
      {% block content %}{% endblock %}

    </div> <!-- /container -->

  </body>
</html>

flask_qa/templates/manageingredients.html
{% extends 'base.html' %}
{% block title %}Manage ingredients{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Manage ingredients</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
                <table style="width:30%; margin:30px auto; border-collapse:collapse;">
                    <tr>
                        <th>Supplier_id</th>
                        <th>Supplier_name</th>
                    </tr>
                    {% for supplier in suppliers %}
                        <tr>
                            <td>{{ supplier.supplier_id }}</td>
                            <td>{{ supplier.supplier_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
                -------------------------------------------------------------------------------------------------
                <table style="width:30%; margin:30px auto; border-collapse:collapse;">
                    <tr>
                        <th>Ingredient_id</th>
                        <th>Ingredient_name</th>
                    </tr>
                    {% for ingredient in ingredients %}
                        <tr>
                            <td>{{ ingredient.ingredient_id }}</td>
                            <td>{{ ingredient.ingredient_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
                -------------------------------------------------------------------------------------------------
                <table style="width:80%; margin:30px auto; border-collapse:collapse;">
                    <tr>
                        <th>ingredientsupplier_id</th>
                        <th>update_date</th>
                        <th>price</th>
                        <th>supplier_name</th>
                        <th>ingredient_name</th>
                    </tr>
                    {% for ingredientsupplier in ingredientsuppliers %}
                        <tr>
                            <td>{{ ingredientsupplier.Ingredientsupplier.supplier_id  }}</td>
                            <td>{{ ingredientsupplier.Ingredientsupplier.update_date  }}</td>
                            <td>{{ ingredientsupplier.Ingredientsupplier.price  }}</td>
                            <td>{{ ingredientsupplier.Supplier.supplier_name  }}</td>
                            <td>{{ ingredientsupplier.Ingredient.ingredient_name  }}</td>
                        </tr>
                    {% endfor %}
                </table>
                -------------------------------------------------------------------------------------------------
                <form class="form-horizontal" method="POST" action="{{ url_for('main.addingredient') }}">
                    <fieldset>
                        <input type="text" class="form-control" name="ingredient_name" id="input_ingredient_name" placeholder="ingredient_name">
                        <button type="submit" class="btn btn-primary">Add ingredients</button>
                    </fieldset>
                </form>
                -------------------------------------------------------------------------------------------------
                <form class="form-horizontal" method="POST" action="{{ url_for('main.addsupplier') }}">
                    <fieldset>
                        <input type="text" class="form-control" name="supplier_name" id="input_supplier_name" placeholder="supplier_name">
                        <button type="submit" class="btn btn-primary">Add ingredient to supply order</button>
                    </fieldset>
                </form>
                -------------------------------------------------------------------------------------------------
                <form class="form-horizontal" method="POST" action="{{ url_for('main.addingredientsupplier') }}">
                    <fieldset>
                        <input type="number" step="any" class="form-control" name="price" id="input_price" placeholder="price">
                        <select name="ingredient_id" font=black>
                            {% for ingredient in ingredients %}
                            <option style="background-color: black" value={{ ingredient.ingredient_id }} font=black>{{ ingredient.ingredient_name }}</option>
                            {% endfor %}
                        </select>
                        <select name="supplier_id" font=black>
                            {% for supplier in suppliers %}
                            <option style="background-color: black" value={{ supplier.supplier_id }} font=black>{{ supplier.supplier_name }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit" class="btn btn-primary">Add ingredient to supply order</button>
                    </fieldset>
                </form>
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/managemenu.html
{% extends 'base.html' %}
{% block title %}managemenu{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Manage Menu</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group"> 
              <h4 class="list-group-item-heading">
                <table style="width:50%; margin:30px auto; border-collapse:collapse;" align="left">
                    <tr>
                        <th>menu_id</th>
                        <th>menu_name</th>
                    </tr>
                    {% for menuitem in menulist %}
                        <tr>
                            <td>{{ menuitem.menu_id }}</td>
                            <td>{{ menuitem.menu_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </h4>
            <h4 class="list-group-item-heading">
                <table style="width:50%; margin:30px auto; border-collapse:collapse;" align="left">
                    <tr>
                        <th>food_id</th>
                        <th>food_name</th>
                    </tr>
                    {% for fooditem in food %}
                        <tr>
                            <td>{{ fooditem.food_id }}</td>
                            <td>{{ fooditem.food_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </h4>
               
              <table style="width:100%; margin:30px auto; border-collapse:collapse;" >
                <tr>
                  <th>Menu_id</th>
                  <th>Menu_name</th>
                  <th>food_name</th>
                  <th>price</th>
                  <th>dish_added_date</th>
                </tr>
            {% for menuitem in menu %}
                <tr>
                    <td>{{ menuitem.Menu.menu_id  }}</td>
                    <td>{{ menuitem.Menu.menu_name  }}</td>
                    <td>{{ menuitem.Food.food_name  }}</td>
                    <td>{{ menuitem.Dish.price  }}</td>
                    <td>{{ menuitem.Dish.dish_date  }}</td>
                </tr>
            {% endfor %}
        </div>
      </div><!-- /.col-lg-12 -->
    </div>
    <div>
        </table>
        -------------------------------------------------------------------------------------------------
        <form class="form-horizontal" method="POST" action="{{ url_for('main.addmenu') }}">
            <fieldset>
                <input type="text" class="form-control" name="menu_name" id="input_menu_name" placeholder="menu_name" required>
                <button type="submit" class="btn btn-primary">Add menu</button>
            </fieldset>
        </form>
        -------------------------------------------------------------------------------------------------
        <form class="form-horizontal" method="POST" action="{{ url_for('main.addfood') }}">
            <fieldset>
                <input type="text" class="form-control" name="food_name" id="input_food_name" placeholder="food_name" required>
                <button type="submit" class="btn btn-primary">Add food</button>
            </fieldset>
        </form>
        -------------------------------------------------------------------------------------------------
        <form class="form-horizontal" method="POST" action="{{ url_for('main.addfoodtomenu') }}">
            <fieldset>
                <input type="number" step="any" class="form-control" name="price" id="input_price" placeholder="price" required>
                <select name="menu_id" font=black>
                    <option value="none" selected disabled hidden> 
                        Select an Option 
                    </option> 
                    {% for menu_item in menulist %}
                    <option style="background-color: black" value={{ menu_item.menu_id }} >{{ menu_item.menu_name }}</option>
                    {% endfor %}
                </select>
                <select name="food_id" font=black value = 1>
                    <option value="none" selected disabled hidden> 
                                Select an Option 
                    </option> 
                    {% for food_item in food %}
                    <option style="background-color: black" value={{ food_item.food_id }} font=black>{{ food_item.food_name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary">Add food to menu</button>
            </fieldset>
        </form>
        -------------------------------------------------------------------------------------------------
        <form class="form-horizontal" method="POST" action="{{ url_for('main.deletefoodfrommenu') }}">
            <fieldset>
                <select name="dish_id" font=black>
                    {% for menu_item in menu %}
                    <option style="background-color: black" value={{ menu_item.Dish.dish_id }} font=black>{{ menu_item.Menu.menu_name }} has {{ menu_item.Food.food_name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary">delete food from menu</button>
            </fieldset>
        </form>
    </div>
{% endblock %}

flask_qa/templates/question.html
{% extends 'base.html' %}
{% block title %}Question{% endblock %}

{% block content %}
<div class="jumbotron">
        <h1>{{ question.question }}</h1>
        <p>{{ question.answer }}</p>
        <p><a class="btn btn-primary btn-lg">Asked By: {{ question.asker.name }}</a></p>
        <p><a class="btn btn-primary btn-lg">Answered By: {{ question.expert.name }}</a></p>
      </div>
{% endblock %}

flask_qa/templates/salesorder.html
{% extends 'base.html' %}
{% block title %}salesorder{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Manage Sales orders</h1>
        <h6>Click to accept salesorder</h6>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
                <form class="form-horizontal" method="POST" action="{{ url_for('main.createsalesorder') }}">
                    <fieldset>
                        <div class="form-group">
                            <h4 class="list-group-item-heading" >click submit to create new sales order</h4>
                            <input type="text" class="form-control" name="salesordertext" id="inputsalesorder" placeholder="salesorder description">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </fieldset>
                </form>
            {% for order in salesorder %}
              <a href="{{ url_for('main.acceptorder', supply_order_id=order.supply_order_id) }}" class="list-group-item {% if order.approval %}active{% endif %}">
                <h4 class="list-group-item-heading">{{ order.supply_order_name }} with approval {{ order.approval }}  has order date {{order.order_date }}</h4>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}